### PR TITLE
Appveyor build (fails on IE 11)

### PR DESCRIPTION
**Pull request by jesperronn**
@antonybudianto I wanted to see if your starter project works on IE. 

This PR shows an error when running the unit tests on IE

See https://ci.appveyor.com/project/jesperronn/angular2-starter/build/6#L997

I am probably missing an IE specific shim or something. Any suggestions?

PS (please don't merge this – at least not until it works )

### CODE REVIEW

**Comment by antonybudianto** [comment]
Hi, thanks for the PR!
Can you put these references in karma `files` array?
```
<!-- 1. Load libraries -->
    <!-- IE required polyfills, in this exact order -->
    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script src="node_modules/systemjs/dist/system-polyfills.js"></script>
    <script src="node_modules/angular2/es6/dev/src/testing/shims_for_IE.js"></script>   
```
If it works, then it just needs a rebase and readme appveyor badge, and I'll merge it :smile:

**Comment by jesperronn** [comment]
@antonybudianto will give your suggestions a try. Sure will rebase when ready, but it's nice for myself do document my own learning process about setting this correctly up :+1: 

Thanks for input!

Remember, though, that you also have to sign into appveyor on behalf of your project in order to tell them to build it :)

**Comment by antonybudianto** [comment]
the build succeed!
now all left:
[ ] rebase
[ ] [this ref](https://github.com/antonybudianto/angular2-starter/pull/42/files#diff-a2a3b7b0c9c3b4b93b4aebf4e3ec3cfbR41) can be removed

**Comment by jesperronn** [comment]
@antonybudianto you have to put the badge on the readme yourself. You can find it in appveyor>settings>badges for the project.

The image has a special URL which I cannot guess.

**Comment by antonybudianto** [comment]
@jesperronn , all great! thanks for the PR! I'll merge it and add the badge later

**Pull request merged**
